### ISSUE TITLE
RuntimeError: Timeout context manager should be used inside a task

### ISSUE THREAD

**Issue by Coddo-Python** [CyanBook/spotipy2#5]
Hi, I was scrolling through my Github explore section and saw this repo, so I wanted to try it out. I simply copy-pasted the demo from the `README.md` (and changed the client id and client token) and it gave me the error `RuntimeError: Timeout context manager should be used inside a task`.

The error seems to originate from `line 25, in get_access_token` inside the `client_credentials_flow.py` file. Full traceback is given below.

## Full Traceback

```
Traceback (most recent call last):
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\test.py", line 28, in <module>
    asyncio.run(get_track_name(input("Insert the track ID: ")))
  File "C:\Users\REMOVED\.pyenv\pyenv-win\versions\3.10.1\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\REMOVED\.pyenv\pyenv-win\versions\3.10.1\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\test.py", line 24, in get_track_name
    track = await s.get_track(track_id)
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\spotipy2\methods\tracks.py", line 18, in get_track
    return Track.from_dict(await self._get(f"tracks/{self.get_id(track_id)}"))
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\spotipy2\client.py", line 83, in _get
    return await self._req("GET", endpoint, params, can_be_cached)
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\spotipy2\client.py", line 55, in _req
    token = await self.auth_flow.get_access_token(self.http)
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\spotipy2\auth\client_credentials_flow.py", line 25, in get_access_token
    async with http.post(
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\venv\lib\site-packages\aiohttp\client.py", line 466, in _request
    with timer:
  File "C:\Users\REMOVED\Documents\Private\Coding\Python\spotipy2\venv\lib\site-packages\aiohttp\helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```

## Installation Details

Operating System: `Windows 11 Home 21H2 22000.556`
Python Version: `3.10.1`
Install Version: [3d351dc](https://github.com/CyanBook/spotipy2/commit/3d351dcd7cc0f835afdef45d0d938b36f3074058)

**Comment by CyanBook** [comment]
You're right.
`aiohttp.ClientSession()` wants to be called inside a coroutine, so moving Spotify() into any async def function should work. Going to push a fix soon for the README.

Thanks for helping and sorry for being late to your issue. School kept me busy for a long time :)
